version: '3.1'

services:

  download-service:
    build: .
    container_name: download-service
    image: oapass/download-service:latest
    env_file: .env
    ports:
      - "${DOWNLOAD_SERVICE_PORT}:${DOWNLOAD_SERVICE_PORT}"

  fcrepo:
    image: oapass/fcrepo:4.7.5-3.2-5@sha256:0bc8bcf2b4804c0c4ba11af2ad3f02ec5a24a442b6d50877148c212dc79c20d1
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"

